# 以下这些应该被写入到nacos配置中心里，然后删除这个文件即可
server:
  port: 8084

spring:
  application:
    name: config-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: xichang810925

custom:
  name: jerry

